.PHONY: clean All

All:
	@echo "----------Building project:[ section6challenge - Debug ]----------"
	@cd "section6challenge" && "$(MAKE)" -f  "section6challenge.mk"
clean:
	@echo "----------Cleaning project:[ section6challenge - Debug ]----------"
	@cd "section6challenge" && "$(MAKE)" -f  "section6challenge.mk" clean
