.PHONY: clean All

All:
	@echo "----------Building project:[ variables - Debug ]----------"
	@cd "variables" && "$(MAKE)" -f  "variables.mk"
clean:
	@echo "----------Cleaning project:[ variables - Debug ]----------"
	@cd "variables" && "$(MAKE)" -f  "variables.mk" clean
